[build]
  command = "npm run build"
  publish = "dist/<your-project-name>/browser"

[functions]
  # Needed to correctly bundle heavy Node modules like firebase-admin
  node_bundler = "esbuild"
  # Ensures the server code is shipped to the function
  external_node_modules = ["firebase-admin"]

[[plugins]]
  package = "@netlify/angular-runtime"
